apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-service-tcp
  namespace: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http-grafana
  - port: 443
    targetPort: 3000
    name: https
#  type: LoadBalancer
#  loadBalancerIP: 192.168.30.206
#  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-grafana
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: LoadBalancer
  loadBalancerIP: 192.168.30.206
  sessionAffinity: ClientIP
